export const INCREMENT = "INCREMENT test";
export const DECREMENT = "DECREMENT";
export const MULTIPLICATION = "MULTIPLICATION";
export const FETCH_REQUEST_USER = "FETCH_REQUEST_USER";
export const FETCH_SUCCESS_USER = "FETCH_SUCCESS_USER";
export const FETCH_ERROR_USER = "FETCH_ERROR_USER";
